http:
  middlewares:
    redirect:
      redirectScheme:
        scheme: https
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/certificate.pem
        keyFile: /etc/certs/certificate-key.pem
