entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    watch: true
    exposedByDefault: false
api:
  dashboard: true
  insecure: true
